version: 0.1.1.{build}

cache:
  - C:\Users\appveyor\AppData\Local\NuGet\Cache

install:
  - curl -L https://github.com/jonathanvdc/compare-test/releases/download/v0.1.2/compare-test.zip > compare-test.zip
  - mkdir bin
  - 7z x compare-test.zip -obin\compare-test
  - nuget restore src\ecsc.sln

build_script:
  - set VERNUM=0.1.1
  - echo %APPVEYOR_REPO_TAG%
  # Build packages as VERNUM-ci{build}
  - ps: if ($env:APPVEYOR_REPO_TAG -eq $True) { $env:PKG_VERSION = $env:VERNUM; } else { $env:PKG_VERSION = "$($env:VERNUM)-ci$($env:APPVEYOR_BUILD_NUMBER)"; }
  - echo %PKG_VERSION%

  - set ASM_VERSION=%VERNUM%.%APPVEYOR_BUILD_NUMBER%
  - echo %ASM_VERSION%
  # Build ecsc
  - msbuild /p:Configuration=Release src\ecsc.sln

after_build:
  # Zip the compiled ecsc binaries, and upload them.
  - mkdir ecsc-build
  - xcopy src\ecsc\bin\Release\*.dll ecsc-build
  - xcopy src\ecsc\bin\Release\*.exe ecsc-build
  - 7z a ecsc.zip %APPVEYOR_BUILD_FOLDER%\ecsc-build\*

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

artifacts:
  - path: ecsc.zip
    name: ecsc

deploy:
  - provider: GitHub
    release: ecsc v$(VERNUM)
    tag: $(APPVEYOR_REPO_TAG_NAME)
    description: 'Release description' # Fill this out later.
    auth_token:
      secure: 693ZX2DdyyjDOqpJaJlUMO1hcMtLbsqMnCLzQVUEq7JjGb+bfEbaB/oMO0b26KZo
    artifact: ecsc.zip # Release the ecsc compiler as an artifact.
    draft: true  # Make this a draft.
    prerelease: false
    on:
      branch: master # Release from master branch only.
      appveyor_repo_tag: true # Deploy on tag push only.

test_script:
  # Run the tests
  - bin\compare-test\compare-test.exe all-tests-windows.test -j
